version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: agenda_bd
    ports:
      - 5433:5432
    volumes:
      - volume-agenda:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=agenda
volumes:
  volume-agenda: